google_project_id       = "sharp-gecko-302118"
google_bucket_name      = "ptynybek19"
deployment_environment  = "dev"
deployment_name         = "hello-world"
credentials             = "fuchicorp-service-account.json"